name: run_dart_code_in_pubsub_message
description: A microservice that runs Dart code received in a Pub/Sub message.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  googleapis: ^11.0.0
  http: ^1.0.0
  shelf: ^1.0.0
  json_utils: ^0.0.0-a1

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.21.0
